### ISSUE TITLE
Missing documentation on plugin page

### ISSUE THREAD

**Issue by rbello** [jenkinsci/devops-portal-plugin#4]
### Describe your use-case which is not covered by existing documentation.

On the plugin page, the documentation is missing: https://plugins.jenkins.io/devops-portal/

Nevertheless, the `README.md` file is present and `pom.xml` file contains the project URL:

```
<artifactId>devops-portal</artifactId>
<url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>
```

I think I followed the guide correctly: https://www.jenkins.io/doc/developer/publishing/documentation/#documenting-plugins

**Comment by rbello** [comment]
Hi @NotMyFault,

Sorry to ask you about this point but I can't get the documentation to come to the plugin site.

Can you help me?

**Comment by NotMyFault** [comment]
Please raise a helpdesk issue if you are seeking for general support with the hosted Jenkins infrastructure: https://github.com/jenkins-infra/helpdesk/issues/new/choose

**Comment by rbello** [comment]
https://github.com/jenkins-infra/helpdesk/issues/3383

**Comment by lemeurherve** [comment]
All good now, this issue can be closed 🙂
